"""Add description field

Revision ID: 270c025252bf
Revises: c690d82b00fd
Create Date: 2025-08-27 16:12:51.334249

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '270c025252bf'
down_revision: Union[str, Sequence[str], None] = 'c690d82b00fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('habit_records_user_id_fkey'), 'habit_records', type_='foreignkey')
    op.drop_column('habit_records', 'user_id')
    op.add_column('habits', sa.Column('description', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('habits', 'description')
    op.add_column('habit_records', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('habit_records_user_id_fkey'), 'habit_records', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
