"""Deleted 'value_achived' due to unusability and changed completed_at logic

Revision ID: a9806244689c
Revises: 270c025252bf
Create Date: 2025-08-30 17:44:47.735971

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a9806244689c'
down_revision: Union[str, Sequence[str], None] = '270c025252bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('habit_records', 'value_achieved')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('habit_records', sa.Column('value_achieved', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
