"""Add Habit, HabitRecord, Folder and relationships

Revision ID: f60b9242d1da
Revises: 2ace156b4611
Create Date: 2025-08-20 09:48:32.700237

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f60b9242d1da'
down_revision: Union[str, Sequence[str], None] = '2ace156b4611'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
